; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
; библиотеки из глобального пути
lib_extra_dirs=C:\Users\Admin\Documents\PlatformIO\Projects\_RSLibs 
upload_protocol = esptool
monitor_filters =
;  default   ; Remove typical terminal control codes from input
  time      ; Add timestamp with milliseconds for each new line
  log2file  ; Log data to a file “platformio-device-monitor-*.log” located in the current working directory
; build_flags = 
;     -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
;     -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG

;monitor_dtr = 0 
;monitor_rts = 0

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
; Скорость загрузки в baud
upload_speed = 115200
; COM-порт для загрузки
upload_port = COM4
monitor_speed = 115200
monitor_port = COM4
board_build.f_cpu = 240000000L   ; Частота в Герцах (240 МГц)
build_flags = 
      -DCONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=4096  ; Увеличивает стек для системных событий Wi-Fi
;     -D CORE_DEBUG_LEVEL=4
;     -DBOARD_HAS_PSRAM
; библиотеки из Github
;lib_deps = robtillaart/DS3232@^0.4.1 

[env:esp32-s3-devkitc-1]
;platform = https://github.com/platformio/platform-espressif32.git   ;Fech lastest support for ESP32
platform = espressif32
board = esp32-s3-devkitc-1    ;ESP32-S3
framework = arduino
upload_speed = 2000000     ;ESP32S3 USB-Serial Converter maximum 2000000bps
upload_port = COM5
monitor_speed = 115200
monitor_port = COM5
debug_tool = esp-builtin
debug_speed = 40000
debug_init_break = break setup
build_type = debug      ;build in debug mode instead of release mode
board_build.f_cpu = 240000000L
;board_build.f_flash = 40000000L
;board_build.flash_mode = DIO

